
%\VignetteIndexEntry{Cardinal development}
%\VignettePackage{Cardinal}
%\VignetteEngine{utils::Sweave}
%\VignetteKeyword{Infrastructure, Bioinformatics, Proteomics, MassSpectrometry}

\documentclass{article}

<<style, eval=TRUE, echo=FALSE, results=tex>>=
BiocStyle::latex()
@

\title{Cardinal development}

\author{Kyle D. Bemis}

\begin{document}

\maketitle

\tableofcontents

\section{Introduction}

<<Cardinal,echo=FALSE,results=hide>>=
options(width=69)
library(Cardinal)
options(Cardinal.verbose=FALSE)
options(Cardinal.progress=FALSE)
@ 
This vignette provides a brief overview of the design and hierarchy of the principle classes us \Rpackage{Cardinal}. It is only of interest to developers, and can be safely ignored by users of \Rpackage{Cardinal}.

\section{\Robject{iSet} and its subclasses}

\subsection{\Robject{iSet}}

Purpose:
\vspace{1em}
\begin{itemize}
\item Virtual class for imaging datasets
\item Analogous to \Robject{eSet} in \Rpackage{Biobase} and \Robject{pSet} in \Rpackage{MSnbase}
\item Coordinate high-throughput pixel-based observations
\item Coordinate high-dimensional feature vectors
\item Coordinate multiple images (samples)
\end{itemize}
<<iSet, results=verbatim>>=
getClass("iSet")
@
Structure:
\vspace{1em}
\begin{itemize}
\item \Robject{imageData}: imaging data, \textit{ImageData}
\item \Robject{pixelData}: pixel covariates, \textit{IAnnotatedDataFrame}
\item \Robject{featureData}: feature covariates, \textit{AnnotatedDataFrame}
\item \Robject{experimentData}: experiment description, \textit{MIAxE}
\item \Robject{protocolData}: protocol description, \textit{AnnotatedDataFrame}
\end{itemize}
\vspace{1em}
See \verb|?"iSet-class"| for more information.

\subsection{\Robject{SImageSet}}

Purpose:
\vspace{1em}
\begin{itemize}
\item Class for pixel-sparse imaging datasets
\item Assumes dataset may be non-rectangular and missing pixels
\item No assumptions about the feature vectors
\end{itemize}
<<SImageSet, results=verbatim>>=
getClass("SImageSet")
@
Structure:
\vspace{1em}
\begin{itemize}
\item \Robject{imageData}: imaging data, \textit{SImageData}
\item \Robject{pixelData}: same as \Robject{iSet}
\item \Robject{featureData}: same as \Robject{iSet}
\item \Robject{experimentData}: same as \Robject{iSet}
\item \Robject{protocolData}: same as \Robject{iSet}
\end{itemize}
\vspace{1em}
See \verb|?"SImageSet-class"| for more information.

\subsection{\Robject{MSImageSet}}

Purpose:
\vspace{1em}
\begin{itemize}
\item Class for pixel-sparse mass spectrometry imaging datasets
\item Assumes dataset may be non-rectangular and missing pixels
\item Assumed the feature vectors are mass spectra
\item Tracks pre-processing steps performed on the dataset
\end{itemize}
<<MSImageSet, results=verbatim>>=
getClass("MSImageSet")
@
Structure:
\vspace{1em}
\begin{itemize}
\item \Robject{imageData}: same as \Robject{SImageSet}
\item \Robject{pixelData}: same as \Robject{iSet}
\item \Robject{featureData}: same as \Robject{iSet}
\item \Robject{experimentData}: experiment description, \textit{MIAPE-Imaging}
\item \Robject{protocolData}: same as \Robject{iSet}
\item \Robject{processingData}: processing description, \textit{MSImageProcess}
\end{itemize}
\vspace{1em}
See \verb|?"MSImageSet-class"| for more information.

\section{\Robject{ImageData} and its subclasses}

\subsection{\Robject{ImageData}}

Purpose:
\vspace{1em}
\begin{itemize}
\item Class for generic storage of imaging data arrays
\item Analogous to \Robject{AssayData} from \Rpackage{Biobase}
\item Data arrays stored in an \textit{environment} to prevent unnecessary copying
\item Can use \textit{immutableEnvironment} to preserve copy-on-write behavior
\end{itemize}
<<ImageData, results=verbatim>>=
getClass("ImageData")
@
Structure:
\vspace{1em}
\begin{itemize}
\item \Robject{data}: data arrays, \textit{environment}
\item \Robject{storageMode}: \textit{immutableEnvironment}, \textit{lockedEnvironment}, or \textit{environment}
\end{itemize}
\vspace{1em}
See \verb|?"ImageData-class"| for more information.

\subsection{\Robject{SImageData}}

Purpose:
\vspace{1em}
\begin{itemize}
\item Class for storage of sparse imaging data arrays
\item Assumed the data are pixel-sparse
\item Higher-dimensional data arrays stored as a matrix with rows as features and columns as pixels
\item Reconstructs the higher-dimensional datacube on-the-fly when subsetted
\end{itemize}
<<SImageData, results=verbatim>>=
getClass("SImageData")
@
Structure:
\vspace{1em}
\begin{itemize}
\item \Robject{data}: same as \Robject{ImageData}
\item \Robject{storageMode}: same as \Robject{ImageData}
\item \Robject{positionArray}: original pixel positions, \textit{array}
\item \Robject{dim}: same as \Robject{matrix}
\item \Robject{dimnames}: same as \Robject{matrix}
\end{itemize}
\vspace{1em}
See \verb|?"SImageData-class"| for more information.

\section{Other classes}

\subsection{\Robject{IAnnotatedDataFrame}}

Purpose:
\vspace{1em}
\begin{itemize}
\item A version of \Robject{AnnotatedDataFrame} for imaging datasets
\item Tracks samples and pixels separately
\item Tracks coordinates of pixels
\end{itemize}
<<IAnnotatedDataFrame, results=verbatim>>=
getClass("IAnnotatedDataFrame")
@
Structure:
\vspace{1em}
\begin{itemize}
\item \Robject{data}: same as \Robject{AnnotatedDataFrame}
\item \Robject{varMetadata}: same as \Robject{AnnotatedDataFrame}
\item \Robject{dimLabels}: same as \Robject{AnnotatedDataFrame}
\end{itemize}
\vspace{1em}
See \verb|?"IAnnotatedDataFrame-class"| for more information.

\subsection{\Robject{MIAPE-Imaging}}

Purpose:
\vspace{1em}
\begin{itemize}
\item The Minimum Information About a Proteomics Experiment for Imaging
\end{itemize}
<<MIAPE, results=verbatim>>=
getClass("MIAPE-Imaging")
@
Structure:
\vspace{1em}
\begin{itemize}
\item \Robject{name}: experimenter name, \textit{character}
\item \Robject{lab}: laboratory where the experimenter was conducted, \textit{character}
\item \Robject{contact}: contact information of the lab and/or experimenter, \textit{character}
\item \Robject{title}: experiment title, \textit{character}
\item \Robject{abstract}: experiment abstract, \textit{character}
\item \Robject{url}: url for the experiment, \textit{character}
\item \Robject{pubMedIds}: relevant PubMed identifies, \textit{character}
\item \Robject{samples}: sample information, \textit{list}
\item \Robject{preprocessing}: pre-processing information, \textit{character}
\item \Robject{other}: other information, \textit{list}
\item \Robject{specimenOrigin}: specimen origin, \textit{character}
\item \Robject{specimenType}: specimen type, \textit{character}
\item \Robject{stainingMethod}: staining method, \textit{character}
\item \Robject{tissueThickness}: tissue thickness, \textit{character}
\item \Robject{tissueWash}: tissue wash, \textit{character}
\item \Robject{embeddingMethod}: embedding method, \textit{character}
\item \Robject{inSituChemistry}: in situ chemistry, \textit{character}
\item \Robject{matrixApplication}: matrix application information, \textit{character}
\item \Robject{pixelSize}: pixel size in micrometers, \textit{character}
\item \Robject{instrumentModel}: instrument model, \textit{character}
\item \Robject{instrumentVendor}: instrument vendor, \textit{character}
\item \Robject{massAnalyzerType}: mass analyzer type (LTQ, TOF, ...), \textit{character}
\item \Robject{ionizationType}: ionization type (MALDI, DESI, ...), \textit{character}
\item \Robject{scanPolarity}: polarity (positive or negative), \textit{character}
\item \Robject{softwareName}: instrument control software, \textit{character}
\item \Robject{softwareVersion}: control software version, \textit{character}
\item \Robject{scanType}: horizontal or vertical line scan, \textit{character}
\item \Robject{scanPattern}: flyback, meandering, or random access, \textit{character}
\item \Robject{scanDirection}: bottom up, left right, right left, or top down, \textit{character}
\item \Robject{lineScanDirection}: bottom up, left right, right left, or top down, \textit{character}
\item \Robject{imageShape}: sample shape information, \textit{character}
\end{itemize}
\vspace{1em}
See \verb|?"MIAPE-Imaging-class"| for more information.

\subsection{\Robject{MSImageProcess}}

Purpose:
\vspace{1em}
\begin{itemize}
\item Class for mass spectral pre-processing information
\end{itemize}
<<MSImageProcess, results=verbatim>>=
getClass("MSImageProcess")
@
Structure:
\vspace{1em}
\begin{itemize}
\item \Robject{files}: file paths to raw data files, \textit{character}
\item \Robject{normalization}: normalization description, \textit{character}
\item \Robject{smoothing}: spectral smoothing description, \textit{character}
\item \Robject{baselineReduction}: baseline correction description, \textit{character}
\item \Robject{spectrumRepresentation}: spectrum type (profile or centroided), \textit{character}
\item \Robject{peakPicking}: peak picking type (area or height), \textit{character}
\item \Robject{centroided}: whether the data has been centroided, \textit{logical}
\item \Robject{history}: pre-processing history, \textit{list}
\item \Robject{CardinalVersion}: version of \Rpackage{Cardinal}, \textit{character}
\end{itemize}
\vspace{1em}
See \verb|?"MSImageProcess-class"| for more information.

\subsection{\Robject{Hashmat}}

Purpose:
\vspace{1em}
\begin{itemize}
\item Class implementing compressed sparse column (CSC) style sparse matrices
\item Allows arbitrary re-ordering of rows in the matrix
\item Designed for storing sparse signals such as processed mass spectra
\end{itemize}
<<Hashmat, results=verbatim>>=
getClass("Hashmat")
@
Structure:
\vspace{1em}
\begin{itemize}
\item \Robject{data}: list of sparse column vectors, \textit{list}
\item \Robject{keys}: keys that determine the rows of the matrix, \textit{character}
\item \Robject{dim}: same as \Robject{matrix}
\item \Robject{dimnames}: same as \Robject{matrix}
\end{itemize}
\vspace{1em}
See \verb|?"MSImageProcess-class"| for more information.

\section{Miscellaneous}

\Rpackage{Cardinal} implements unit tests using \Rpackage{testthat}.

\section{Session info}

<<results=tex, echo=FALSE>>=
toLatex(sessionInfo())
@

\end{document}
