
#### Define new generics from base R ####
setGeneric("as.array")
setGeneric("as.matrix")
setGeneric("names")
setGeneric("names<-")
setGeneric("rownames<-")
setGeneric("colnames<-")

#### Basic accessor, setter, and manipulation ####
setGeneric("coord", function(object) standardGeneric("coord"))
setGeneric("coord<-", function(object, value) standardGeneric("coord<-"))
setGeneric("coordinates", function(object) coord(object))
setGeneric("coordinates<-", function(object, value) coord(object, value))
setGeneric("coordLabels", function(object) standardGeneric("coordLabels"))
setGeneric("coordLabels<-", function(object, value) standardGeneric("coordLabels<-"))
setGeneric("features", function(object, ...) standardGeneric("features"))
setGeneric("flipHorizontal", function(object, ...) standardGeneric("flipHorizontal"))
setGeneric("flipVertical", function(object, ...) standardGeneric("flipVertical"))
setGeneric("iData", function(object) standardGeneric("iData"))
setGeneric("iData<-", function(object, value) standardGeneric("iData<-"))
setGeneric("imageData", function(object) standardGeneric("imageData"))
setGeneric("imageData<-", function(object, value) standardGeneric("imageData<-"))
setGeneric("intensities", function(object, ...) standardGeneric("intensities"))
setGeneric("mergePeaks", function(peaks, ...) standardGeneric("mergePeaks"))
setGeneric("metaData", function(object) standardGeneric("metaData"))
setGeneric("metaData<-", function(object, value) standardGeneric("metaData<-"))
setGeneric("mz", function(object) standardGeneric("mz")) # use MSnbase generic?
setGeneric("mz<-", function(object, value) standardGeneric("mz<-"))
setGeneric("neighbors", function(object, r, ...) standardGeneric("neighbors"))
setGeneric("numFeatures", function(object) standardGeneric("numFeatures"))
setGeneric("numPixels", function(object) standardGeneric("numPixels"))
setGeneric("peaks", function(object) standardGeneric("peaks")) # use mzR generic?
setGeneric("peaks<-", function(object, value) standardGeneric("peaks<-"))
setGeneric("pixels", function(object, ...) standardGeneric("pixels"))
setGeneric("pixelData", function(object) standardGeneric("pixelData"))
setGeneric("pixelData<-", function(object, value) standardGeneric("pixelData<-"))
setGeneric("pixelNames", function(object) standardGeneric("pixelNames"))
setGeneric("pixelNames<-", function(object, value) standardGeneric("pixelNames<-"))
setGeneric("poolPeaks", function(peaks, ...) standardGeneric("poolPeaks"))
setGeneric("positionArray", function(object) standardGeneric("positionArray"))
setGeneric("positionArray<-", function(object, value) standardGeneric("positionArray<-"))
setGeneric("processingData", function(object) standardGeneric("processingData")) # use MSnbase generic?
setGeneric("processingData<-", function(object, value) standardGeneric("processingData<-")) # use MSnbase generic?
setGeneric("regeneratePositions", function(object) standardGeneric("regeneratePositions"))
setGeneric("roiBind", function(object, ...) standardGeneric("roiBind"))
setGeneric("rotateLeft", function(object, ...) standardGeneric("rotateLeft"))
setGeneric("rotateRight", function(object, ...) standardGeneric("rotateRight"))
setGeneric("sliceBind", function(object, ...) standardGeneric("sliceBind"));
setGeneric("spectra", function(object) standardGeneric("spectra")) # use MSnbase generic?
setGeneric("spectra<-", function(object, value) standardGeneric("spectra<-"))

setGeneric("msiInfo", function(object) standardGeneric("msiInfo"))
setGeneric("specimenOrigin", function(object) standardGeneric("specimenOrigin"))
setGeneric("specimenOrigin<-", function(object, value) standardGeneric("specimenOrigin<-"))
setGeneric("specimenType", function(object) standardGeneric("specimenType"))
setGeneric("specimenType<-", function(object, value) standardGeneric("specimenType<-"))
setGeneric("stainingMethod", function(object) standardGeneric("stainingMethod"))
setGeneric("stainingMethod<-", function(object, value) standardGeneric("stainingMethod<-"))
setGeneric("tissueThickness", function(object) standardGeneric("tissueThickness"))
setGeneric("tissueThickness<-", function(object, value) standardGeneric("tissueThickness<-"))
setGeneric("tissueWash", function(object) standardGeneric("tissueWash"))
setGeneric("tissueWash<-", function(object, value) standardGeneric("tissueWash<-"))
setGeneric("embeddingMethod", function(object) standardGeneric("embeddingMethod"))
setGeneric("embeddingMethod<-", function(object, value) standardGeneric("embeddingMethod<-"))
setGeneric("inSituChemistry", function(object) standardGeneric("inSituChemistry"))
setGeneric("inSituChemistry<-", function(object, value) standardGeneric("inSituChemistry<-"))
setGeneric("matrixApplication", function(object) standardGeneric("matrixApplication"))
setGeneric("matrixApplication<-", function(object, value) standardGeneric("matrixApplication<-"))
setGeneric("pixelSize", function(object) standardGeneric("pixelSize"))
setGeneric("pixelSize<-", function(object, value) standardGeneric("pixelSize<-"))
setGeneric("instrumentModel", function(object) standardGeneric("instrumentModel")) # use MSnbase generic?
setGeneric("instrumentModel<-", function(object, value) standardGeneric("instrumentModel<-"))
setGeneric("instrumentVendor", function(object) standardGeneric("instrumentVendor"))
setGeneric("instrumentVendor<-", function(object, value) standardGeneric("instrumentVendor<-"))
setGeneric("massAnalyzerType", function(object) standardGeneric("massAnalyzerType"))
setGeneric("massAnalyzerType<-", function(object, value) standardGeneric("massAnalyzerType<-"))
setGeneric("ionizationType", function(object) standardGeneric("ionizationType"))
setGeneric("ionizationType<-", function(object, value) standardGeneric("ionizationType<-"))
setGeneric("scanPolarity", function(object) standardGeneric("scanPolarity"))
setGeneric("scanPolarity<-", function(object, value) standardGeneric("scanPolarity<-"))
setGeneric("softwareName", function(object) standardGeneric("softwareName")) # use MSnbase generic?
setGeneric("softwareName<-", function(object, value) standardGeneric("softwareName<-"))
setGeneric("softwareVersion", function(object) standardGeneric("softwareVersion")) # use MSnbase generic?
setGeneric("softwareVersion<-", function(object, value) standardGeneric("softwareVersion<-"))
setGeneric("scanType", function(object) standardGeneric("scanType"))
setGeneric("scanType<-", function(object, value) standardGeneric("scanType<-"))
setGeneric("scanPattern", function(object) standardGeneric("scanPattern"))
setGeneric("scanPattern<-", function(object, value) standardGeneric("scanPattern<-"))
setGeneric("scanDirection", function(object) standardGeneric("scanDirection"))
setGeneric("scanDirection<-", function(object, value) standardGeneric("scanDirection<-"))
setGeneric("lineScanDirection", function(object) standardGeneric("lineScanDirection"))
setGeneric("lineScanDirection<-", function(object, value) standardGeneric("lineScanDirection<-"))
setGeneric("imageShape", function(object) standardGeneric("imageShape"))
setGeneric("imageShape<-", function(object, value) standardGeneric("imageShape<-"))

setGeneric("prochistory", function(object) standardGeneric("prochistory"))
setGeneric("prochistory<-", function(object, value) standardGeneric("prochistory<-"))
setGeneric("files", function(object) standardGeneric("files"))
setGeneric("files<-", function(object, value) standardGeneric("files<-"))
setGeneric("normalization", function(object) standardGeneric("normalization"))
setGeneric("normalization<-", function(object, value) standardGeneric("normalization<-"))
setGeneric("smoothing", function(object) standardGeneric("smoothing"))
setGeneric("smoothing<-", function(object, value) standardGeneric("smoothing<-"))
setGeneric("baselineReduction", function(object) standardGeneric("baselineReduction"))
setGeneric("baselineReduction<-", function(object, value) standardGeneric("baselineReduction<-"))
setGeneric("spectrumRepresentation", function(object) standardGeneric("spectrumRepresentation"))
setGeneric("spectrumRepresentation<-", function(object, value) standardGeneric("spectrumRepresentation<-"))
setGeneric("peakPicking", function(object) standardGeneric("peakPicking"))
setGeneric("peakPicking<-", function(object, value) standardGeneric("peakPicking<-"))
setGeneric("centroided", function(object) standardGeneric("centroided")) # use mzR generic?
setGeneric("centroided<-", function(object, value) standardGeneric("centroided<-"))

#### Processing and data transformation ####
setGeneric("smoothSignal", function(object, ...) standardGeneric("smoothSignal"))
setGeneric("reduceBaseline", function(object, ...) standardGeneric("reduceBaseline"))
setGeneric("peakPick", function(object, ...) standardGeneric("peakPick"))
setGeneric("peakAlign", function(object, ...) standardGeneric("peakAlign"))

#### Processing and data transformation (Old) ####
setGeneric("alignPeaks", function(peaks, reference, ...) standardGeneric("alignPeaks"))
setGeneric("assessQuality", function(object, ...) standardGeneric("assessQuality"))
setGeneric("binSpectra", function(object, peaks, ...) standardGeneric("binSpectra"))
setGeneric("calibrateSegmentation", function(object, reference, ...) standardGeneric("calibrateSegmentation"))
setGeneric("coregisterImages", function(object, ...) standardGeneric("coregisterImages"))
setGeneric("crop", function(object, ...) standardGeneric("crop"))
setGeneric("detectPeaks", function(object, ...) standardGeneric("detectPeaks"))
setGeneric("estimateBaseline", function(object, ...) standardGeneric("estimateBaseline"))
setGeneric("estimateNoise", function(object, ...) standardGeneric("estimateNoise"));
setGeneric("likPlot", function(object, ...) standardGeneric("likPlot"))
setGeneric("logLik", function(object, ...) standardGeneric("logLik"))
setGeneric("removeBaseline", function(object, ...) standardGeneric("removeBaseline"))
setGeneric("removeNoise", function(object, ...) standardGeneric("removeNoise"))
setGeneric("resampleSpectra", function(object, peaks, ...) standardGeneric("resampleSpectra"))
setGeneric("selectPeaks", function(object, ...) standardGeneric("selectPeaks"))
setGeneric("selectPixels", function(object, ...) standardGeneric("selectPixels"))
setGeneric("selectROI", function(object, ...) standardGeneric("selectROI"))
setGeneric("spectralApply", function(object, MARGIN, FUN, ...) standardGeneric("spectralApply"))
setGeneric("standardizeTotalImageIntensity", function(object, ...) standardGeneric("standardizeTotalImageIntensity"));
setGeneric("standardizeTotalIonCurrent", function(object, ...) standardGeneric("standardizeTotalIonCurrent"))

#### Apply-like methods ####
setGeneric("cvApply", function(.object, .fun, ...) standardGeneric("cvApply"))
setGeneric("featureApply", function(.object, .fun, ...) standardGeneric("featureApply"))
setGeneric("pixelApply", function(.object, .fun, ...) standardGeneric("pixelApply"))

#### Plotting and visualization ####
setGeneric("summaryPlot", function(object, reference, ...) standardGeneric("summaryPlot"))
setGeneric("trellisImage", function(x, ...) standardGeneric("trellisImage"))
setGeneric("trellisPlot", function(x, ...) standardGeneric("trellisPlot"))
setGeneric("volume", function(x, ...) standardGeneric("volume"))

#### Statistical analysis and tools ####
setGeneric("crossValidate", function(x, y, ...) standardGeneric("crossValidate"))
setGeneric("OPLS", function(x, y, ...) standardGeneric("OPLS"))
setGeneric("PCA", function(x, ...) standardGeneric("PCA"))
setGeneric("PLS", function(x, y, ...) standardGeneric("PLS"))
setGeneric("predict", function(object, ...) standardGeneric("predict"))
setGeneric("spatialClassify", function(object, ...) standardGeneric("spatialClassify"))
setGeneric("spatialCluster", function(object, ...) standardGeneric("spatialCluster"))
setGeneric("spatialKMeans", function(object, ...) standardGeneric("spatialKMeans"))
setGeneric("spatialSparseClassify", function(object, labels, ...) standardGeneric("spatialSparseClassify"))
setGeneric("spatialSparseCluster", function(object, ...) standardGeneric("spatialSparseCluster"))
setGeneric("spatialSparseKMeans", function(object, ...) standardGeneric("spatialSparseKMeans"))
setGeneric("summary", function(object, ...) standardGeneric("summary"))

