setGeneric("alignPeaks", function(peaks, reference, ...) standardGeneric("alignPeaks"))
setGeneric("assessQuality", function(object, ...) standardGeneric("assessQuality"))
setGeneric("binSpectra", function(object, peaks, ...) standardGeneric("binSpectra"))
setGeneric("calibrateSegmentation", function(object, reference, ...) standardGeneric("calibrateSegmentation"))
setGeneric("coord", function(object) standardGeneric("coord"))
setGeneric("coord<-", function(object, value) standardGeneric("coord<-"))
setGeneric("coordNames", function(object) standardGeneric("coordNames"))
setGeneric("coordNames<-", function(object, value) standardGeneric("coordNames<-"))
setGeneric("coregisterImages", function(object, ...) standardGeneric("coregisterImages"))
setGeneric("crop", function(object, ...) standardGeneric("crop"))
setGeneric("crossValidate", function(x, y, ...) standardGeneric("crossValidate"))
setGeneric("detectPeaks", function(object, ...) standardGeneric("detectPeaks"))
setGeneric("estimateBaseline", function(object, ...) standardGeneric("estimateBaseline"))
setGeneric("estimateNoise", function(object, ...) standardGeneric("estimateNoise"));
setGeneric("features", function(object, mz, ...) standardGeneric("features"))
setGeneric("flipHorizontal", function(object, ...) standardGeneric("flipHorizontal"))
setGeneric("flipVertical", function(object, ...) standardGeneric("flipVertical"))
setGeneric("generatePositionArray", function(object, ...) standardGeneric("generatePositionArray"))
setGeneric("intensities", function(object, ...) standardGeneric("intensities"))
setGeneric("isBinned", function(object) standardGeneric("isBinned"))
setGeneric("isBinned<-", function(object, value) standardGeneric("isBinned<-"))
setGeneric("isPeaks", function(object) standardGeneric("isPeaks"))
setGeneric("isPeaks<-", function(object, value) standardGeneric("isPeaks<-"))
setGeneric("isResampled", function(object) standardGeneric("isResampled"))
setGeneric("isResampled<-", function(object, value) standardGeneric("isResampled<-"))
setGeneric("likPlot", function(object, ...) standardGeneric("likPlot"))
setGeneric("mergePeaks", function(peaks, ...) standardGeneric("mergePeaks"))
setGeneric("metaData", function(object) standardGeneric("metaData"))
setGeneric("metaData<-", function(object, value) standardGeneric("metaData<-"))
# setGeneric("mz", function(object) standardGeneric("mz")) # use MSnbase generic
setGeneric("mz<-", function(object, value) standardGeneric("mz<-"))
setGeneric("neighbors", function(object, r, ...) standardGeneric("neighbors"))
setGeneric("numFeatures", function(object) standardGeneric("numFeatures"))
setGeneric("numPixels", function(object) standardGeneric("numPixels"))
setGeneric("OPLS", function(x, y, ...) standardGeneric("OPLS"))
setGeneric("PCA", function(x, ...) standardGeneric("PCA"))
# setGeneric("peaks", function(object) standardGeneric("peaks")) # use mzR generic
setGeneric("peaks<-", function(object, value) standardGeneric("peaks<-"))
setGeneric("pixels", function(object, coord, ...) standardGeneric("pixels"))
setGeneric("pixelData", function(object) standardGeneric("pixelData"))
setGeneric("pixelData<-", function(object, value) standardGeneric("pixelData<-"))
setGeneric("pixelNames", function(object) standardGeneric("pixelNames"))
setGeneric("pixelNames<-", function(object, value) standardGeneric("pixelNames<-"))
setGeneric("PLS", function(x, y, ...) standardGeneric("PLS"))
setGeneric("poolPeaks", function(peaks, ...) standardGeneric("poolPeaks"))
setGeneric("regeneratePositions", function(object) standardGeneric("regeneratePositions"))
setGeneric("removeBaseline", function(object, ...) standardGeneric("removeBaseline"))
setGeneric("removeNoise", function(object, ...) standardGeneric("removeNoise"))
setGeneric("resampleSpectra", function(object, peaks, ...) standardGeneric("resampleSpectra"))
setGeneric("roiBind", function(object, ...) standardGeneric("roiBind"))
setGeneric("rotateLeft", function(object, ...) standardGeneric("rotateLeft"))
setGeneric("rotateRight", function(object, ...) standardGeneric("rotateRight"))
setGeneric("selectPeaks", function(object, ...) standardGeneric("selectPeaks"))
setGeneric("selectPixels", function(object, ...) standardGeneric("selectPixels"))
setGeneric("selectROI", function(object, ...) standardGeneric("selectROI"))
setGeneric("sliceBind", function(object, ...) standardGeneric("sliceBind"));
setGeneric("spatialClassify", function(object, ...) standardGeneric("spatialClassify"))
setGeneric("spatialCluster", function(object, ...) standardGeneric("spatialCluster"))
setGeneric("spatialKMeans", function(object, ...) standardGeneric("spatialKMeans"))
setGeneric("spatialSparseClassify", function(object, labels, ...) standardGeneric("spatialSparseClassify"))
setGeneric("spatialSparseCluster", function(object, ...) standardGeneric("spatialSparseCluster"))
setGeneric("spatialSparseKMeans", function(object, ...) standardGeneric("spatialSparseKMeans"))
# setGeneric("spectra", function(object) standardGeneric("spectra")) # use MSnbase generic
setGeneric("spectra<-", function(object, value) standardGeneric("spectra<-"))
setGeneric("spectralApply", function(object, MARGIN, FUN, ...) standardGeneric("spectralApply"))
setGeneric("standardizeTotalImageIntensity", function(object, ...) standardGeneric("standardizeTotalImageIntensity"));
setGeneric("standardizeTotalIonCurrent", function(object, ...) standardGeneric("standardizeTotalIonCurrent"))
setGeneric("summaryPlot", function(object, reference, ...) standardGeneric("summaryPlot"))
setGeneric("trellisImage", function(x, ...) standardGeneric("trellisImage"))
setGeneric("trellisPlot", function(x, ...) standardGeneric("trellisPlot"))
setGeneric("trellisVolume", function(x, ...) standardGeneric("trellisVolume"))	
setGeneric("unload", function(object, ...) standardGeneric("unload"))
setGeneric("volume", function(x, ...) standardGeneric("volume"))

